[PARAM]
do_train = True
do_predict = True
do_lower_case = True
train_file = src/train-v1.1.json
train_batch_size = 2
learning_rate = 3e-5
num_train_epochs = 2.0
max_seq_length = 320
doc_stride = 128
bert_model = src/KTNET-large
predict_file = dev-v1.1.json
output_dir = predictions.json
max_query_length = 64
predict_batch_size = 8
warmup_proportion = 0.1
n_best_size = 20
max_answer_length = 30
verbose_logging = False
no_cuda = False
seed = 42
gradient_accumulation_steps = 1
local_rank = -1
optimize_on_cpu = False
fp16 = False
loss_scale = 128
